### ISSUE TITLE
Scrolling behaviour is buggy

### ISSUE THREAD

**Issue by arjenvanderende** [Fundynamic/dune2themaker4j#175]
The scrolling behaviour in windowed mode is weird and seems buggy. I can only scroll when my mouse pointer is positioned _outside_ of the window, instead of at the border of the viewport. Furthermore, when the game is scrolling and then loses focus (by clicking outside of the window), the game gets confused and scrolls back-and-forth very rapidly.

I've made a short video for clarification:

[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/3MfYyda12Ck/0.jpg)](https://youtu.be/3MfYyda12Ck)

**Comment by stefanhendriks** [comment]
Interesting, I can't seem to reproduce the back-and-forth thing, needs investigation on that part.

As for the 'border does not scroll' thing, [that probably is a bug within here](https://github.com/Fundynamic/dune2themaker4j/blob/master/src/main/java/com/fundynamic/d2tm/game/rendering/gui/GuiComposite.java#L80).

**Comment by stefanhendriks** [comment]
I believe we have determined this is expected behaviour, we have seen this in C&C as well.
