### ISSUE TITLE
To make it easier to customize the game I want to Load game data from an external file

### ISSUE THREAD

**Issue by stefanhendriks** [Fundynamic/dune2themaker4j#29]
For instance, the `StructureRepository` initializes itself in the constructor. This should be done via a configuration file, or perhaps dynamic language script? (ie Jython?)

Purpose: to make configuration and setup of game easier to customize.

In the original Dune (2) or C&C series, there where INI files.

I don't think we need to use that. Rather we could use XML (easy to parse - but verbose), or YML, or something with a hierarchy.

**Comment by RiderRockon** [comment]
Would that include structure functionality itself, or just things like size and appearances?

**Comment by stefanhendriks** [comment]
As much as possible. Although I envision that behaviour would become scriptable.

**Comment by stefanhendriks** [comment]
After https://github.com/Fundynamic/dune2themaker4j/tree/refactor/remove-entity-to-cell-association we're going to work on this
