### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by stefanhendriks** [Fundynamic/dune2themaker4j#31]
With more complex interactions with the game coming, the need for a GUI arises.

It looks like Slick2D has some GUI's , [this stackexchange post has quite a nice answer](http://gamedev.stackexchange.com/questions/43739/how-to-add-text-box-in-slick2d)

basically boils down to:
- do it yourself (see link post above)
- [NiftyUI](https://github.com/void256/nifty-gui) (saw recent update of 25th 2015)
- [TWL](http://twl.l33tlabs.org/) (not sure when latest release was)

Decision has to be made at some time.

**Comment by RiderRockon** [comment]
Speaking from a position where I've written on myself several times, I would absolutely recommend using an existing package. It's just way too much work to write something like that, and it's hardly worth the time and effort.

**Comment by stefanhendriks** [comment]
I intent to use time wisely so "doing yourself" is my least favorable option.

**Comment by stefanhendriks** [comment]
so far a DIY GUI worked well enough. Especially since the GUI is not that much. No need to drag windows, etc. So for now this is closed.
