### ISSUE TITLE
Introduce concept of projectiles

### ISSUE THREAD

**Issue by stefanhendriks** [Fundynamic/dune2themaker4j#70]
At the moment units deal direct damage without having anything 'flying over' to the enemy unit. (ie a bullet, missile, etc).

I want to have projectiles being spawned, fired to the enemy and on landing inflict the damage.

Acceptance criteria
- [x] Trikes and Quads spawn bullets
- [x] bullets travel at given speed directly (as if it is a line) to destination
- [x] upon arrival *only then* damage will be dealt
- [x] upon arrival a 'landed' animation is shown. Ie a missile would explode, a bullet will show a different sprite.

**Comment by RiderRockon** [comment]
Will the damage be dealt to "whatever is in this cell" or the target unit directly?

**Comment by stefanhendriks** [comment]
Whatever is on the cell will receive damage.

**Comment by stefanhendriks** [comment]
Now with pull request merged to use absolute coordinates, we can continue working on this issue. Projectiles will be rendered on the map as expected.

**Comment by stefanhendriks** [comment]
progress so far: https://www.youtube.com/watch?v=o8JFidUmHUs

**Comment by stefanhendriks** [comment]
we can spawn bullets now and have explosions: https://www.youtube.com/watch?v=XglryMQEZjo&list=PLGJc4IZyoBW0rdEfpvgFH2sHiB3JIR-BN&index=2

**Comment by stefanhendriks** [comment]
- [ ] facing is bugged
- [ ] entityData should be used everywhere (consistently)
