### ISSUE TITLE
Units can be ordered to attack enemy unit until destroyed

### ISSUE THREAD

**Issue by stefanhendriks** [Fundynamic/dune2themaker4j#84]
Ie attack mode. 

Atm if you click on enemy unit you spawn a projectile. Instead:

- [x] unit should move close enough to enemy
- [x] when close enough, unit starts firing projectiles
- [x] when enemy unit is destroyed, the unit 'quits' attack mode
- [x] Before firing, unit should check if target is still in range, and if not, move
- [x] Before firing, unit should check if it is facing the correct direction for firing, and if not, rotate.

**Comment by pdl** [comment]
Also:

- Before firing, unit should check if target is still in range, and if not, move
- Before firing, unit should check if it is facing the correct direction for firing, and if not, rotate.

**Comment by stefanhendriks** [comment]
yes @pdl good points . The second point requires #63
